<?
$newsDetail = $this->newsDetail;
$newsDetail = $newsDetail[0];
// var_dump($newsDetail);die;
?>
<div class="main-content-inner content-width">
  
  <!-- Main Column / Sidebar -->  
  <div class="column-container">
    
    <!-- Main Column -->    
    <div class="column-three-qtr">
      
      <!-- Blog Post -->      
      <div class="blog-post actual-post">
        <!-- Title -->
        <h1><?= $newsDetail['news_title']?></h1>
        <!-- Meta -->
        <div class="blog-meta">
          <div class="meta-item"><div class="meta-title published">Дата:</div><a href="#"><?= date('d F Y', strtotime($newsDetail['news_date']))?></a></div>
          <div class="meta-item"><div class="meta-title views">Просмотры:</div><a href="#"><?= $newsDetail['news_views']?></a></div>
        </div>
        
        <!-- Content -->        
        <div class="blog-content">
          <!-- Paragraph -->
          <p><?= $newsDetail['news_short_content']?></p>
          <div class="media">
            <div id="portfolio-blog-slider-container">
              <div id="portfolio-blog-slider">
                
                <!-- Actual Images -->                
                <img alt="" src="/public/images/placeholders/preview11.jpg" class="fullwidth">
                <img alt="" src="/public/images/placeholders/preview12.jpg" class="fullwidth">                
                <!-- END Actual Images -->
                
              </div>
              
              <!-- Slide Controls -->              
              <div class="portfolio-blog-slider-controls">
                <div id="portfolio-blog-slider-prev"></div>
                <div id="portfolio-blog-slider-next"></div>
              </div>              
              <!-- END Slide Controls -->              

            </div>
          </div>          
          <!-- END Image -->          

          <!-- H3 Title -->
          <h3>Департамент маркетинга и продаж экономит медиамикс</h3>
          <!-- Paragraph -->
          <p><?= $newsDetail['news_content']?></p>
        </div>        
        <!-- END Content -->        

      </div>      
      <!-- END Blog Post -->
      
      <!-- Share Links -->      
      <ul class="post-sharing">
        <li><a href="#"><i class="fa fa-facebook"></i><div class="tooltip">Поделиться в Facebook</div></a></li>
        <li><a href="#"><i class="fa fa-twitter"></i><div class="tooltip">Поделиться в Twitter</div></a></li>
        <li><a href="#"><i class="fa fa-linkedin-square"></i><div class="tooltip">Поделиться в LinkedIn</div></a></li>
        <li><a href="#"><i class="fa fa-pinterest"></i><div class="tooltip">Поделиться в Pinterest</div></a></li>
        <li><a href="#"><i class="fa fa-google-plus"></i><div class="tooltip">Поделиться в Google+</div></a></li>
      </ul>      
      <!-- END Share Links -->
      
      <!-- Divider -->      
      <div class="divider"></div>      
      <!-- END Divider -->

      <!-- Reader Comments -->      
      <div class="comments">
        <h2>Комментарии к статьи</h2>

        <?foreach ($this->comments as $value) {?>
          <!-- Comment -->        
          <div class="comment">
            <!-- Username -->
            <div class="username">
              <a href="#"><?= $value['CommentName']?></a> пишет:
            </div>
            <!-- Date -->
            <div class="date">
              <?= date('d F Y', strtotime($value['CommentDate']))?>
            </div>
            <!-- Message -->
            <div class="message">
              <p><?= $value['CommentBody']?></p>
            </div>
            <!-- Reply Link -->
            <div class="link">
              <a href="#">Ответить</a>
            </div>
          </div>        
          <!-- END Comment -->
        <?}?>        

      </div>      
      <!-- END Reader Comments -->

      <!-- Divider -->      
      <div class="divider"></div>      
      <!-- END Divider -->
      
      <!-- Post Comment Form -->      
      <div class="comment-form">
        <h2>Оставить комментарий</h2>
        <form id="comment-form" name="comment-form" method="post" action="/news/<?= $newsDetail['cat_code']?>/<?= $newsDetail['news_id']?>">
          <!-- Textbox -->
          <input type="text" name="name" placeholder="Имя *" required>
          <!-- Comment box -->
          <textarea name="comment" maxlength="200" placeholder="Сообщение * (макс. 200симв.)" required></textarea>
          <!-- Submit Button -->
          <input type="submit" name="submitComment" class="accent" value="Готово">
        </form>
      </div>      
      <!-- END Post Comment Form -->

    </div>    
    <!-- END Main Column -->   

    <!-- Sidebar -->    
    <div class="column-one-fourth sidebar">
      
      <!-- Categories -->      
      <div class="sidebar-widget categories">
        <!-- Title -->
        <h3>Категории новостей</h3>
        <!-- Category Links -->
        <?foreach ($this->allCategories as $value) {?>
          <a href="/news/<?= $value['cat_code']?>/"><?= $value['cat_name']?></a>
        <?}?>
      </div>      
      <!-- END Categories -->
      
      <!-- Latest Project -->      
      <div class="sidebar-widget project">
        <!-- Title -->
        <h3>Новость дня</h3>
        <?foreach ($this->topNews as $value) {?>          
          <!-- Image -->
          <a href="#" class="image-link"><img alt="" src="/public/images/placeholders/preview4.jpg" class="fullwidth"></a>
          <!-- Project Title -->
          <h3 class="sub-title"><a href="/news/<?= $value['cat_code']?>/<?= $value['news_id']?>"><?= $value['news_title']?></a></h3>
          <!-- Tags -->
          <div class="tags"><?= $value['cat_name']?></div>
        <?}?>
      </div>      
      <!-- END Latest Project -->
      
      <!-- Popular Posts -->      
      <div class="sidebar-widget posts">
        <!-- Title -->
        <h3>Последнее</h3>
        <?foreach ($this->lastNews as $value) {?>
          <!-- Post -->
          <div class="post">
            <!-- Image Column -->
            <div class="img-column">
              <a href="/news/<?= $value['cat_code']?>/<?= $value['news_id']?>" class="image-link mini">
                <img alt="" src="/public/images/placeholders/preview9-mini.jpg" class="fullwidth"></a>
            </div>
            <!-- Content Column -->
            <div class="content-column">
              <!-- Post Title -->
              <h3 class="sub-title"><a href="/news/<?= $value['cat_code']?>/<?= $value['news_id']?>"><?= $value['news_title']?></a></h3>
              <!-- Date -->
              <div class="date"><?= date('d F Y', strtotime($value['news_date']))?></div>
            </div>
          </div>
          <!-- END Post -->
        <?}?>
      </div>
      <!-- END Popular Posts -->

    </div>    
    <!-- END Sidebar -->    

  </div>  
  <!-- END Main Column / Sidebar -->  

</div>